### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by tonydle** [tonydle/ping_pong_ur3#3]
Hey @fehinti I'm looking at what you have added
I just have a few questions:

1. The UR3 robot model: did you use my .ply files for the model of the UR3? Why are the ply files being used (excluding the first link) bigger than the original files I added to the repo? There're still small (< 5MB each) but they're about 10x bigger than my original files. I noticed that it loaded in noticably slower and it might affect performance.
2. I can add my robot controller I wrote for A1, although it's likely that we will build another controller that can follow joint trajectory, have velocity controls, collisions avoidance and other stuff. ATM "RobotController" is empty
3. I might modify "EnvironmentComponent" too, And add in my codes from A1. And maybe change the name to something shorter :P

Everything else looks all good. I will be adding my stuff from Unity soon .. it's taking longer to port things over from my Capstone repo than I expected

**Comment by fehinti** [comment]
> Hey @fehinti I'm looking at what you have added
> I just have a few questions:
> 
> 1. The UR3 robot model: did you use my .ply files for the model of the UR3? Why are the ply files being used (excluding the first link) bigger than the original files I added to the repo? There're still small (< 5MB each) but they're about 10x bigger than my original files. I noticed that it loaded in noticably slower and it might affect performance.
> 2. I can add my robot controller I wrote for A1, although it's likely that we will build another controller that can follow joint trajectory, have velocity controls, collisions avoidance and other stuff. ATM "RobotController" is empty
> 3. I might modify "EnvironmentComponent" too, And add in my codes from A1. And maybe change the name to something shorter :P
> 
> Everything else looks all good. I will be adding my stuff from Unity soon .. it's taking longer to port things over from my Capstone repo than I expected

Answers:
1. Hey man I didn't end up using your files because I already started editing the files I had earlier and went on with it. We can decimate the ones we have in there to reduce the size of the files to improve our performance.

2. If you take a look at the new branch called RobotControl, you would see the new class of the controller and I think you can add the stuff you need to add in that class.

3. Yh sure go an and add the new stuff, in there and good idea to change the name, I couldn't come up with something shorter.

**Comment by tonydle** [comment]
@fehinti ohh i see
Yeah I got the links of the UR3 down to ~ 500KB each and the model still looked decent (on MATLAB anyways), the model im using on Unity is still high-res. We can do the decimating later

How are you planning on writing that RobotControl?

Should we have a meeting? Maybe tomorrow morning?

**Comment by fehinti** [comment]
Yh a meeting would be great and tomorrow morning is just fine.
