### ISSUE TITLE
Unity files added in RobotControl

### ISSUE THREAD

**Issue by tonydle** [tonydle/ping_pong_ur3#4]
Hey @fehinti why are there unity files added ("PingPongSim") in the RobotControl branch?
I'm still working on the UR3UnitySim branch and hasn't merged it with develop yet so these files should not be there

**Comment by fehinti** [comment]
> Hey @fehinti why are there unity files added ("PingPongSim") in the RobotControl branch?
> I'm still working on the UR3UnitySim branch and hasn't merged it with develop yet so these files should not be there

Hey @tonydle, what happened was I viewed the work on your branch and while the files were opened I think I switched branches back to the RobotControl branch, so sorry about that. How do you suggest I fix it?
